# Generated by Django 2.2.9 on 2020-01-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('DELAYED', 'DELAYED'), ('FLAPPING', 'FLAPPING'), ('FAILED', 'FAILED')], db_index=True, default='OK', max_length=10),
        ),
    ]
