# Generated by Django 2.2.9 on 2020-01-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_job_last_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_notification',
            field=models.DateTimeField(null=True),
        ),
    ]
