# Generated by Django 2.2.9 on 2020-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_execution_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
