# Generated by Django 2.2.9 on 2020-02-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_job_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
