# Generated by Django 2.2.9 on 2020-06-19 11:33

from django.db import migrations, models

from cronorc_server.main.models import Host


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_job_period'),
    ]

    operations = [
        migrations.RunSQL(Host.VIEW_DEFINITION),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('last_execution', models.DateTimeField(null=True)),
                ('last_notification', models.DateTimeField(null=True)),
                ('job_count', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'main_host',
                'managed': False,
            },
        )
    ]
